= iOS development and deployment with fastlane
Sangjoon Moon <iceblue.dev@gmail.com>
v1.0, 2016-04-05
:hp-tags: HubPress, fastlane, ios, deployment, development

== setting up `fastlane`
.  `fastlane init` command in the project folder
This will prompt you for your Apple ID in order run produce and enable sigh and deliver.

.. fastlane tools
- produce : create new iOS apps on iTunes Connect and Dev Portal
- sigh : create, renew, download and repair provisioning profiles
- deliver : upload ipa or pkg files, app screenshots and more to iTunes Connect

.. results with `init` command
- Created a fastlane folder
- Moved existing deliver and snapshot configuration into the fastlane folder (if they existed).
- Created fastlane/Appfile, which stores your Apple ID and Bundle Identifier.
- Created fastlane/Fastfile, which stores your deployment pipelines.

. Configure the `Fastfile`
Configure `Fastfile` as your situation. For example:

- New App Store releases
- Beta Builds for TestFlight or HockeyApp
- Only testing (unit and integration tests)
- In House distribution

== Example

 $ fastlane ios appstore

Using an default Fastfile, fastlane can create a new app version in Dev Portal. With fastlane, you don't need to create the new version app in Dev Portal.


== Problems 

If you make the new app manually in Dev Portal, after `fastlane init` command, you would be get an trouble in the next app version following with fastlane deployments. Fastlane will use the previous version app information and screenshots when you invoke fastlane `lane` action. (i.e. `fastlane ios appstore`)  

How to sync the current AppStore information before fastlane get started. I don't know how to solve this issue yet. Does anyone knows about it? Please let me know.